// web/src/components/Quadrant/index.tsx
import './styles.scss'

import { QuadrantModel } from 'models/View'
import React from 'react'

interface QuadrantValue {
  value: number;
  label: string;
}

interface Props {
  view: QuadrantModel
}

export default function Quadrant({ view }: Props) {
  const  { nw, ne, sw, se, title } = view
  return (
    <div className='quadrant'>
      <div className='quadrant-header'>{title}</div>
      <div className='quadrant-body'>
        <div className='quadrant-ne'>
          <div className='quadrant-value'>{ne.value}</div>
          <div className='quadrant-label'>{ne.label}</div>
        </div>
        <div className='quadrant-nw'>
          <div className='quadrant-value'>{nw.value}</div>
          <div className='quadrant-label'>{nw.label}</div>
        </div>
        <div className='quadrant-se'>
          <div className='quadrant-value'>{se.value}</div>
          <div className='quadrant-label'>{se.label}</div>
        </div>
        <div className='quadrant-sw'>
          <div className='quadrant-value'>{sw.value}</div>
          <div className='quadrant-label'>{sw.label}</div>
        </div>
      </div>
    </div>
  )
}

// web/angular/src/app/layout/view/quadrant/quadrant.component.ts
import { Component, Input, OnChanges, SimpleChanges } from '@angular/core';
import { QuadrantValue, QuadrantView } from 'src/app/models/content';

@Component({
  selector: 'app-view-quadrant',
  templateUrl: './quadrant.component.html',
  styleUrls: ['./quadrant.component.scss'],
})
export class QuadrantComponent implements OnChanges {
  @Input() view: QuadrantView;

  title: string;
  nw: QuadrantValue = emptyQuadrantValue;
  ne: QuadrantValue = emptyQuadrantValue;
  sw: QuadrantValue = emptyQuadrantValue;
  se: QuadrantValue = emptyQuadrantValue;

  constructor() {}

  ngOnChanges(changes: SimpleChanges): void {
    if (changes.view.currentValue) {
      const view = changes.view.currentValue as QuadrantView;
      this.nw = view.config.nw;
      this.ne = view.config.ne;
      this.sw = view.config.sw;
      this.se = view.config.se;
    }
  }
}

const emptyQuadrantValue = { value: '', label: '' };

<div class="card">
  <div class="card-block">
    <div class="card-title">{{ title }}</div>
    <div class="quadrant">
      <div class="quadrant--body">
        <div class="quadrant--ne">
          <div class="quadrant-value">{{ ne.value }}</div>
          <div class="quadrant-label">{{ ne.label }}</div>
        </div>
        <div class="quadrant--nw">
          <div class="quadrant-value">{{ nw.value }}</div>
          <div class="quadrant-label">{{ nw.label }}</div>
        </div>
        <div class="quadrant--se">
          <div class="quadrant-value">{{ se.value }}</div>
          <div class="quadrant-label">{{ se.label }}</div>
        </div>
        <div class="quadrant--sw">
          <div class="quadrant-value">{{ sw.value }}</div>
          <div class="quadrant-label">{{ sw.label }}</div>
        </div>
      </div>
    </div>
  </div>
</div>
